version: "3"
 
services:
  pythonmelero:
    image: "franciscomelero/pythonmelero"
    #Puerto de exposición y escucha
    ports:
      - "5000:5000"
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
